import java.util.*;

public class PatternStringIndex {
	public static void main(String[] args){
		long start = System.currentTimeMillis();
		String str = "abababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababaabababababababababababababababababababbabababababababababababababababababababababao";
		String pattern = "baa";
		Solution(str,pattern,str.length(),pattern.length());
		long end = System.currentTimeMillis();
		System.out.println((end - start)/1000.0);
		System.out.println(str.length());
	}
	
	static void Solution(String str,String pattern,int sl,int pl){
		char[] strs = new char[sl];
		int ind = 0;
		for(char element : str.toCharArray()){
			strs[ind++] = element;
		}
		int[] patt = new int[26];
		for(int i = 0;i<pl;i++){
			patt[pattern.charAt(i) - 'a']++;
		}
		ArrayList<Integer> list = new ArrayList<>();
		
		int[] checking = new int[26];
		for(int i = 0;i<pl;i++){
			checking[strs[i] - 'a']++;
		}
		int checkind = 0;
		for(int i = pl;i <sl;i++){ 
		
			System.out.println(Arrays.toString(checking));
			if(Arrays.equals(checking,patt)){
				list.add(i-pl);
			}
 			checking[strs[checkind++] - 'a']--;
			checking[strs[i] - 'a']++;
		}
		
		
		System.out.println(Arrays.toString(strs));
		System.out.println(Arrays.toString(patt));
		System.out.println(list);
	}
}